# Site settings
author: Shirl Williams
title: My Data Science Journey
header-img: img/home-bg.png
email: shirl.williams@icloud.com
copyright_name: Shirl Williams
description: > # this means to ignore newlines until "baseurl:"
  Projects, descriptions, tutorials, my journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  shirlwilliams

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
